version: '3.8'

services:
  app:
    build: .
    container_name: alpes-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  scheduler:
    build: .
    container_name: alpes-api-scheduler
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - app
    command: php artisan schedule:work

  db:
    image: mysql:8.0
    container_name: alpes-api-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: alpes
      MYSQL_USER: alpes
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: alpes-api-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: alpes
      PMA_PASSWORD: secret
    depends_on:
      - db

volumes:
  db_data:
